apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: frontend
  labels:
    tier: frontend
spec:
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: tes-nginx
        image: nginx:1.17-alpine
