apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld
spec:
  completions: 3
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sleep", "20"]
      restartPolicy: Never
