apiVersion: v1
kind: Pod
metadata:
  name: cpu-pod-2
spec:
  containers:
  - name: quota-container
    image: busybox
    imagePullPolicy: IfNotPresent
    
    command: ['sh', '-c', 'echo Pod is Running ; sleep 3600']
    resources:
      requests:
        cpu: "150m"
      limits:
        cpu: "250m"
                 
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
